name: CI
on:
  push:
    branches:
    - main
jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt-get install packages
      run: sudo apt-get update -qq &&
           sudo apt-get install --no-install-recommends -y
               gcc
               git
               make
               libsdl1.2-dev
               libsdl-image1.2-dev
    - name: build
      run: make
    - name: test
      run: make test
  linux-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt-get install packages
      run: sudo apt-get update -qq &&
           sudo apt-get install --no-install-recommends -y
               git
               make
               clang
               libsdl1.2-dev
               libsdl-image1.2-dev
    - name: build
      run: make CC=clang
    - name: test
      run: make test CC=clang
  mac-gcc:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: brew install deps
      run: brew update && brew install
               sdl sdl_image
    - name: build
      run: make
    - name: test
      run: make test
  mac-clang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: brew install deps
      run: brew update && brew install
               sdl sdl_image
    - name: build
      run: make CC=clang
    - name: test
      run: make test CC=clang
